# Copy from OpenDAL
name: Setup Rust Builder
description: 'Prepare Rust Build Environment'
inputs:
  rust_version:
    required: false
    description: using rust-toolchain version
    default: nightly-2023-04-11
runs:
  using: "composite"
  steps:
    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-cargo
    - name: Setup rust related environment variables
      shell: bash
      # FIXME: using toolchain nightly version
      run: |
        rustup default ${{ github.inputs.rust_version }}
        rustup component add rustfmt
        rustup component add clippy